# Generated by Django 4.2.5 on 2023-10-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_rename_animal_id_animalmedia_animal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animalmedia',
            old_name='main',
            new_name='is_main',
        ),
        migrations.RemoveField(
            model_name='animalmedia',
            name='media_link',
        ),
        migrations.AddField(
            model_name='animalmedia',
            name='media',
            field=models.ImageField(default='', upload_to='animal_images/'),
            preserve_default=False,
        ),
    ]
