# Generated by Django 4.2.30 on 2026-04-25 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_alter_animalmedia_media'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['-start_time']},
        ),
    ]
