# Generated by Django 6.0.4 on 2026-05-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_alter_schedule_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelterWeekdayHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], unique=True)),
                ('is_closed', models.BooleanField(default=False, help_text='When checked, no visits are offered on this day.')),
                ('opens_at', models.TimeField(blank=True, null=True)),
                ('closes_at', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'shelter weekday hours',
                'verbose_name_plural': 'shelter weekday hours',
                'ordering': ['weekday'],
            },
        ),
    ]
