# Generated by Django 6.0.4 on 2026-05-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_shelter_weekday_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelterDateOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_date', models.DateField(db_index=True, unique=True)),
                ('is_closed', models.BooleanField(default=False, help_text='When checked, no visits on this date (e.g. holiday).')),
                ('opens_at', models.TimeField(blank=True, null=True)),
                ('closes_at', models.TimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, help_text='Optional note (e.g. holiday name).', max_length=255)),
            ],
            options={
                'verbose_name': 'shelter date override',
                'verbose_name_plural': 'shelter date overrides',
                'ordering': ['calendar_date'],
            },
        ),
    ]
