# Generated by Django 6.0.4 on 2026-05-23

import django.core.validators
from django.db import migrations, models

from animals.scheduling.defaults import (
    DEFAULT_SHELTER_CLOSE,
    DEFAULT_SHELTER_OPEN,
    DEFAULT_SLOT_STEP_MINUTES,
)


def seed_shelter_hours_and_booking_settings(apps, schema_editor):
    ShelterWeekdayHours = apps.get_model("animals", "ShelterWeekdayHours")
    ShelterBookingSettings = apps.get_model("animals", "ShelterBookingSettings")
    for weekday in range(7):
        ShelterWeekdayHours.objects.get_or_create(
            weekday=weekday,
            defaults={
                "is_closed": False,
                "opens_at": DEFAULT_SHELTER_OPEN,
                "closes_at": DEFAULT_SHELTER_CLOSE,
            },
        )

    ShelterBookingSettings.objects.get_or_create(
        pk=1,
        defaults={"slot_step_minutes": DEFAULT_SLOT_STEP_MINUTES},
    )


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0007_shelter_date_override"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShelterBookingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slot_step_minutes",
                    models.PositiveSmallIntegerField(
                        default=DEFAULT_SLOT_STEP_MINUTES,
                        help_text="Minutes between offered start times in the slot picker.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
            ],
            options={
                "verbose_name": "shelter booking settings",
                "verbose_name_plural": "shelter booking settings",
            },
        ),
        migrations.RunPython(
            seed_shelter_hours_and_booking_settings,
            migrations.RunPython.noop,
        ),
    ]
