# Generated by Django 4.2.5 on 2023-09-17 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='tag_id',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='animal_id',
            new_name='animal',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='user_id',
            new_name='user',
        ),
    ]
